basic.pause(3000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 200)
basic.pause(500)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(100)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 255)
basic.pause(392)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(2000)
